theme: jekyll-theme-dinky
title: super-resolution-testing
description: Testing procedure for Super Resolution
show_downloads: true
google_analytics: UA-3278327-4
github:
  zip_url: https://github.com/ydecastro/super-resolution-testing/raw/master/super-resolution-testing.zip
  is_user_page: true
  is_project_page: false
  owner_url: https://ydecastro.github.io/
